project_name: blox

builds:
  - id: blox
    main: ./cli/blox/main.go
    binary: blox
    # Default is `-s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.builtBy=goreleaser`.
    ldflags:
      - -s -w -X github.com/cueblox/blox/cmd.Version={{.Version}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - GO111MODULE=on
      - MACOSX_DEPLOYMENT_TARGET=10.11

dockers:
  - image_templates:
      - "ghcr.io/cueblox/blox:{{ .Tag }}-amd64"
    ids:
      - blox
    use_buildx: true
    build_flag_templates:
      - --platform=linux/amd64
  - image_templates:
      - "ghcr.io/cueblox/blox:{{ .Tag }}-arm64"
    ids:
      - blox
    use_buildx: true
    build_flag_templates:
      - --platform=linux/arm64

docker_manifests:
  - name_template: "ghcr.io/cueblox/blox:latest"
    image_templates:
      - "ghcr.io/cueblox/blox:{{ .Tag }}-amd64"
      - "ghcr.io/cueblox/blox:{{ .Tag }}-arm64"

  - name_template: "ghcr.io/cueblox/blox:{{ .Tag }}"
    image_templates:
      - "ghcr.io/cueblox/blox:{{ .Tag }}-amd64"
      - "ghcr.io/cueblox/blox:{{ .Tag }}-arm64"

brews:
  - name: blox
    tap:
      owner: cueblox
      name: homebrew-tap
      token: "{{ .Env.TAP_WRITE_KEY }}"
    folder: formula

    commit_author:
      name: CueBlox
      email: support@cueblox.com

    homepage: "https://github.com/cueblox/"
    description: "CueBlox"
    license: "MIT"
