project_name: blox

before:
  hooks:
    - go mod tidy
    - ./scripts/completions.sh

builds:
  - id: blox
    main: ./cmd/blox
    binary: blox
    # Default is `-s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.builtBy=goreleaser`.
    ldflags:
    - -s -w -X main.version={{ .Version }} -X main.commit={{ .Commit }} -X main.date={{ .CommitDate }} -X main.builtBy=goreleaser
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - GO111MODULE=on
      - MACOSX_DEPLOYMENT_TARGET=10.11

dockers:
  - image_templates:
      - "ghcr.io/cueblox/blox:{{ .Tag }}-amd64"
    ids:
      - blox
    use_buildx: true
    build_flag_templates:
      - --platform=linux/amd64
  - image_templates:
      - "ghcr.io/cueblox/blox:{{ .Tag }}-arm64"
    ids:
      - blox
    use_buildx: true
    build_flag_templates:
      - --platform=linux/arm64

docker_manifests:
  - name_template: "ghcr.io/cueblox/blox:latest"
    image_templates:
      - "ghcr.io/cueblox/blox:{{ .Tag }}-amd64"
      - "ghcr.io/cueblox/blox:{{ .Tag }}-arm64"

  - name_template: "ghcr.io/cueblox/blox:{{ .Tag }}"
    image_templates:
      - "ghcr.io/cueblox/blox:{{ .Tag }}-amd64"
      - "ghcr.io/cueblox/blox:{{ .Tag }}-arm64"
      
changelog:
  filters:
    exclude:
      - Merge
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
  format_overrides:
    - goos: windows
      format: zip
  files:
    - README.md
    - LICENSE
    - completions/*

brews:
  - name: blox
    tap:
      owner: cueblox
      name: homebrew-tap
      token: "{{ .Env.TAP_WRITE_KEY }}"
    folder: Formula

    commit_author:
      name: CueBlox
      email: support@cueblox.com

    homepage: "https://github.com/cueblox/"
    description: "CueBlox"
    license: "MIT"
    test: |
      system "#{bin}/blox -v"
    install: |-
      bin.install "blox"
      bash_completion.install "completions/blox.bash" => "blox"
      zsh_completion.install "completions/blox.zsh" => "_blox"
      fish_completion.install "completions/blox.fish"
